package com.wuzhizhan.mybatis.generate.plugin;

import org.mybatis.generator.api.GeneratedJavaFile;
import org.mybatis.generator.api.IntrospectedColumn;
import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.ShellCallback;
import org.mybatis.generator.api.dom.java.CompilationUnit;
import org.mybatis.generator.api.dom.java.FullyQualifiedJavaType;
import org.mybatis.generator.api.dom.java.Interface;
import org.mybatis.generator.api.dom.java.JavaVisibility;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.Parameter;
import org.mybatis.generator.api.dom.java.TypeParameter;
import org.mybatis.generator.config.JavaClientGeneratorConfiguration;
import org.mybatis.generator.internal.DefaultShellCallback;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Generates a generic {@code MyBatisBaseDao} interface and lets mapper interfaces extend it.
 * This is a reimplementation of the classic CommonDAOInterface plugin compatible with MBG 1.4+.
 */
public class CommonDaoInterfacePlugin extends PluginAdapter {

    private static final FullyQualifiedJavaType PARAM_ANNOTATION_TYPE =
            new FullyQualifiedJavaType("org.apache.ibatis.annotations.Param");
    private static final FullyQualifiedJavaType SERIALIZABLE_TYPE =
            new FullyQualifiedJavaType("java.io.Serializable");

    private final Map<String, Method> methodTemplates = new LinkedHashMap<>();
    private final ShellCallback shellCallback = new DefaultShellCallback(false);

    @Override
    public boolean validate(List<String> warnings) {
        return true;
    }

    @Override
    public List<GeneratedJavaFile> contextGenerateAdditionalJavaFiles(IntrospectedTable introspectedTable) {
        List<GeneratedJavaFile> answer = new ArrayList<>();
        JavaClientGeneratorConfiguration clientConfig = context.getJavaClientGeneratorConfiguration();
        if (clientConfig == null) {
            return answer;
        }
        String targetProject = clientConfig.getTargetProject();
        String targetPackage = clientConfig.getTargetPackage();
        if (targetProject == null || targetPackage == null) {
            return answer;
        }

        Interface baseInterface = new Interface(targetPackage + ".MyBatisBaseDao");
        baseInterface.setVisibility(JavaVisibility.PUBLIC);
        baseInterface.addJavaDocLine("/**");
        baseInterface.addJavaDocLine(" * MyBatis base DAO interface automatically generated by idea-mybatis plugin.");
        baseInterface.addJavaDocLine(" * @param <Model> domain type");
        baseInterface.addJavaDocLine(" * @param <PK> primary key type");
        baseInterface.addJavaDocLine(" * @param <E> example criteria type");
        baseInterface.addJavaDocLine(" */");

        // add generic parameters
        baseInterface.addTypeParameter(new TypeParameter("Model"));
        TypeParameter pkParameter = new TypeParameter("PK",
                Collections.singletonList(SERIALIZABLE_TYPE));
        baseInterface.addTypeParameter(pkParameter);
        baseInterface.addTypeParameter(new TypeParameter("E"));

        baseInterface.addImportedType(PARAM_ANNOTATION_TYPE);
        baseInterface.addImportedType(new FullyQualifiedJavaType("java.util.List"));
        baseInterface.addImportedType(SERIALIZABLE_TYPE);

        if (methodTemplates.isEmpty()) {
            return answer;
        }

        methodTemplates.values().forEach(method -> baseInterface.addMethod(new Method(method)));

        GeneratedJavaFile javaFile = new GeneratedJavaFile(baseInterface,
                targetProject,
                context.getProperty("javaFileEncoding"),
                context.getJavaFormatter());

        try {
            File directory = shellCallback.getDirectory(
                    targetProject,
                    baseInterface.getType().getPackageName());
            File file = new File(directory, javaFile.getFileName());
            if (file.exists()) {
                return answer;
            }
        } catch (Exception ignored) {
            return answer;
        }

        answer.add(javaFile);
        return answer;
    }

    @Override
    public boolean clientGenerated(Interface interfaze,
                                   IntrospectedTable introspectedTable) {
        interfaze.addJavaDocLine("/**");
        interfaze.addJavaDocLine(" * " + interfaze.getType().getShortName() + "继承基类");
        interfaze.addJavaDocLine(" */");

        String baseInterfaceTypeName = interfaze.getType().getPackageName() + ".MyBatisBaseDao";
        FullyQualifiedJavaType superInterface = new FullyQualifiedJavaType(baseInterfaceTypeName);

        FullyQualifiedJavaType modelType = new FullyQualifiedJavaType(introspectedTable.getBaseRecordType());
        FullyQualifiedJavaType primaryKeyType = calculatePrimaryKeyType(introspectedTable, modelType);
        FullyQualifiedJavaType exampleType = new FullyQualifiedJavaType(introspectedTable.getExampleType());

        superInterface.addTypeArgument(modelType);
        superInterface.addTypeArgument(primaryKeyType);
        superInterface.addTypeArgument(exampleType);

        interfaze.addImportedType(modelType);
        interfaze.addImportedType(primaryKeyType);
        interfaze.addImportedType(exampleType);
        interfaze.addImportedType(superInterface);
        interfaze.addSuperInterface(superInterface);

        return true;
    }

    // region method interception
    @Override
    public boolean clientCountByExampleMethodGenerated(Method method, Interface interfaze,
                                                       IntrospectedTable introspectedTable) {
        interceptExampleParam(method);
        return false;
    }

    @Override
    public boolean clientDeleteByExampleMethodGenerated(Method method, Interface interfaze,
                                                        IntrospectedTable introspectedTable) {
        interceptExampleParam(method);
        return false;
    }

    @Override
    public boolean clientDeleteByPrimaryKeyMethodGenerated(Method method, Interface interfaze,
                                                           IntrospectedTable introspectedTable) {
        interceptPrimaryKeyParam(method);
        return false;
    }

    @Override
    public boolean clientInsertMethodGenerated(Method method, Interface interfaze,
                                               IntrospectedTable introspectedTable) {
        interceptModelParam(method);
        return false;
    }

    @Override
    public boolean clientInsertSelectiveMethodGenerated(Method method, Interface interfaze,
                                                        IntrospectedTable introspectedTable) {
        interceptModelParam(method);
        return false;
    }

    @Override
    public boolean clientSelectByExampleWithBLOBsMethodGenerated(Method method, Interface interfaze,
                                                                 IntrospectedTable introspectedTable) {
        interceptExampleParam(method);
        setListReturnType(method);
        return false;
    }

    @Override
    public boolean clientSelectByExampleWithoutBLOBsMethodGenerated(Method method, Interface interfaze,
                                                                    IntrospectedTable introspectedTable) {
        interceptExampleParam(method);
        setListReturnType(method);
        return false;
    }

    @Override
    public boolean clientSelectByPrimaryKeyMethodGenerated(Method method, Interface interfaze,
                                                           IntrospectedTable introspectedTable) {
        interceptPrimaryKeyParam(method);
        method.setReturnType(new FullyQualifiedJavaType("Model"));
        return false;
    }

    @Override
    public boolean clientUpdateByExampleSelectiveMethodGenerated(Method method, Interface interfaze,
                                                                 IntrospectedTable introspectedTable) {
        interceptModelAndExampleParam(method);
        return false;
    }

    @Override
    public boolean clientUpdateByExampleWithBLOBsMethodGenerated(Method method, Interface interfaze,
                                                                 IntrospectedTable introspectedTable) {
        interceptModelAndExampleParam(method);
        return false;
    }

    @Override
    public boolean clientUpdateByExampleWithoutBLOBsMethodGenerated(Method method, Interface interfaze,
                                                                    IntrospectedTable introspectedTable) {
        interceptModelAndExampleParam(method);
        return false;
    }

    @Override
    public boolean clientUpdateByPrimaryKeySelectiveMethodGenerated(Method method, Interface interfaze,
                                                                    IntrospectedTable introspectedTable) {
        interceptModelParam(method);
        return false;
    }

    @Override
    public boolean clientUpdateByPrimaryKeyWithBLOBsMethodGenerated(Method method, Interface interfaze,
                                                                    IntrospectedTable introspectedTable) {
        interceptModelParam(method);
        return false;
    }

    @Override
    public boolean clientUpdateByPrimaryKeyWithoutBLOBsMethodGenerated(Method method, Interface interfaze,
                                                                       IntrospectedTable introspectedTable) {
        interceptModelParam(method);
        return false;
    }

    //endregion

    private void interceptExampleParam(Method method) {
        method.getParameters().clear();
        method.addParameter(new Parameter(new FullyQualifiedJavaType("E"), "example"));
        recordMethod(method);
    }

    private void interceptPrimaryKeyParam(Method method) {
        method.getParameters().clear();
        method.addParameter(new Parameter(new FullyQualifiedJavaType("PK"), "id"));
        recordMethod(method);
    }

    private void interceptModelParam(Method method) {
        method.getParameters().clear();
        method.addParameter(new Parameter(new FullyQualifiedJavaType("Model"), "record"));
        recordMethod(method);
    }

    private void interceptModelAndExampleParam(Method method) {
        List<Parameter> parameters = method.getParameters();
        if (parameters.size() == 1) {
            interceptExampleParam(method);
            return;
        }
        method.getParameters().clear();

        Parameter record = new Parameter(new FullyQualifiedJavaType("Model"), "record");
        record.addAnnotation("@Param(\"record\")");
        method.addParameter(record);

        Parameter example = new Parameter(new FullyQualifiedJavaType("E"), "example");
        example.addAnnotation("@Param(\"example\")");
        method.addParameter(example);

        recordMethod(method);
    }

    private void setListReturnType(Method method) {
        FullyQualifiedJavaType listType = FullyQualifiedJavaType.getNewListInstance();
        listType.addTypeArgument(new FullyQualifiedJavaType("Model"));
        method.setReturnType(listType);
    }

    private void recordMethod(Method method) {
        Method template = new Method(method);
        template.getBodyLines().clear();
        template.setDefault(false);
        template.setAbstract(true);
        template.setFinal(false);
        template.setNative(false);
        template.setStatic(false);
        template.setVisibility(JavaVisibility.PUBLIC);

        methodTemplates.put(buildMethodKey(template), template);
    }

    private String buildMethodKey(Method method) {
        StringBuilder sb = new StringBuilder(method.getName()).append('(');
        method.getParameters().forEach(param ->
                sb.append(param.getType().getFullyQualifiedName()).append(','));
        sb.append(")->");
        Optional<FullyQualifiedJavaType> returnType = method.getReturnType();
        sb.append(returnType.map(FullyQualifiedJavaType::getFullyQualifiedName).orElse("void"));
        return sb.toString();
    }

    private FullyQualifiedJavaType calculatePrimaryKeyType(IntrospectedTable introspectedTable,
                                                           FullyQualifiedJavaType modelType) {
        List<IntrospectedColumn> pkColumns = introspectedTable.getPrimaryKeyColumns();
        if (pkColumns.size() > 1) {
            String javaModelPackage = context.getJavaModelGeneratorConfiguration().getTargetPackage();
            String domainObjectName = introspectedTable.getFullyQualifiedTable().getDomainObjectName();
            return new FullyQualifiedJavaType(javaModelPackage + "." + domainObjectName + "Key");
        }
        if (pkColumns.size() == 1) {
            return pkColumns.get(0).getFullyQualifiedJavaType();
        }
        return modelType;
    }
}

